require "core.configs.comment"
require "core.configs.colorscheme"
require "core.configs.lualine"
require "core.configs.nvim-tree"
require "core.configs.treesitter"
require "core.configs.telescope"
-- require "core.configs.indentline"
require "core.configs.toggleterm"
-- require "core.configs.lsp"
-- require "core.configs.autocommands"
-- require "core.configs.cmp"
-- require "core.configs.gitsigns"
-- require "core.configs.autopairs"
-- require "core.configs.bufferline"
-- require "core.configs.project"
-- require "core.configs.illuminate"
-- require "core.configs.alpha"
